function(andromeda_message msg)
  if (NOT FTXUI_QUIET)
    message(STATUS "${msg}")
  endif()
endfunction()

andromeda_message("┌─ FTXUI options ─────────────────────")
andromeda_message("│ FTXUI_BUILD_EXAMPLES     : ${FTXUI_BUILD_EXAMPLES}")
andromeda_message("│ FTXUI_BUILD_TESTS        : ${FTXUI_BUILD_TESTS}")
andromeda_message("│ FTXUI_BUILD_TESTS_FUZZER : ${FTXUI_BUILD_TESTS_FUZZER}")
andromeda_message("│ FTXUI_CLANG_TIDY         : ${FTXUI_CLANG_TIDY}")
andromeda_message("│ FTXUI_DEV_WARNINGS       : ${FTXUI_DEV_WARNINGS}")
andromeda_message("│ FTXUI_ENABLE_COVERAGE    : ${FTXUI_ENABLE_COVERAGE}")
andromeda_message("│ FTXUI_ENABLE_INSTALL     : ${FTXUI_ENABLE_INSTALL}")
andromeda_message("│ FTXUI_QUIET              : ${FTXUI_QUIET}")
andromeda_message("└─────────────────────────────────────")
