function(andromeda_message msg)
  if (NOT ANDROMEDAUI_QUIET)
    message(STATUS "${msg}")
  endif()
endfunction()

andromeda_message("┌─ FTXUI options ─────────────────────")
andromeda_message("│ ANDROMEDAUI_BUILD_EXAMPLES     : ${ANDROMEDAUI_BUILD_EXAMPLES}")
andromeda_message("│ ANDROMEDAUI_BUILD_TESTS        : ${ANDROMEDAUI_BUILD_TESTS}")
andromeda_message("│ ANDROMEDAUI_BUILD_TESTS_FUZZER : ${ANDROMEDAUI_BUILD_TESTS_FUZZER}")
andromeda_message("│ ANDROMEDAUI_CLANG_TIDY         : ${ANDROMEDAUI_CLANG_TIDY}")
andromeda_message("│ ANDROMEDAUI_DEV_WARNINGS       : ${ANDROMEDAUI_DEV_WARNINGS}")
andromeda_message("│ ANDROMEDAUI_ENABLE_COVERAGE    : ${ANDROMEDAUI_ENABLE_COVERAGE}")
andromeda_message("│ ANDROMEDAUI_ENABLE_INSTALL     : ${ANDROMEDAUI_ENABLE_INSTALL}")
andromeda_message("│ ANDROMEDAUI_QUIET              : ${ANDROMEDAUI_QUIET}")
andromeda_message("└─────────────────────────────────────")
